### ISSUE TITLE
The maximize and minimize buttons are not displaying properly

### ISSUE THREAD

**Issue by s0urcelab** [Losses/rune#112]
**Describe the bug**
The maximize and minimize buttons are not displaying properly.

**To Reproduce**
1. run rune
2. See error

**Expected behavior**
should display buttons

**Screenshots**
![image](https://github.com/user-attachments/assets/58a93647-346f-417c-a449-203ce946dd21)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: LTSC 21H2 19044.1645

**Comment by Losses** [comment]
Interesting, let me try to fix that today or tomorrow, thank you for testing it!

**Comment by Losses** [comment]
Hi, since I don't have a device running Windows 10, the fix for this bug is based on guesswork. I've made some attempts on v0.0.0-dev.12. Would you be willing to give it a try?

**Comment by s0urcelab** [comment]
> Hi, since I don't have a device running Windows 10, the fix for this bug is based on guesswork. I've made some attempts on v0.0.0-dev.12. Would you be willing to give it a try?

I think you mean v0.0.0-alpha.12 ?
Already tried, it works perfect!

![image](https://github.com/user-attachments/assets/b4ac4cac-386a-4f39-b2bd-e3e00383ff34)
