### ISSUE TITLE
macOS: commit `3dca3b93bc` break the Control Strip

### ISSUE THREAD

**Issue by XMLHexagram** [Losses/rune#122]
**Describe the bug**
After commit `3dca3b93bc` can not interactive with Control Strip on macOS any more.

**To Reproduce**
1. Play a random song
2. Try to use Control Strip

**Expected behavior**
It should work and response hover, click and drag gesture.

**Screenshots**
![CleanShot 2024-11-26 at 21 53 59@2x](https://github.com/user-attachments/assets/2f71993e-860a-46c3-ad02-4afd1d9897ef)

**Desktop:**
 - OS: macOS

**Comment by XMLHexagram** [comment]
Caused by the changes in `controller_buttons.dart`.

**Comment by XMLHexagram** [comment]
https://github.com/Losses/rune/blob/b8ab31e055f12fbdc6f5e2ffe63f85b120db5e0e/lib/widgets/playback_controller/controller_buttons.dart#L86-L88

Caused by new `MouseRegion` widget.

**Comment by XMLHexagram** [comment]
I only have macOS dev environment. But I believe this bug not only happens on macOS.

**Comment by Losses** [comment]
Fixed.
