### ISSUE TITLE
Accessing a Mix playlist or Mixes during library analysis causes interface crash

### ISSUE THREAD

**Issue by puff-dayo** [Losses/rune#148]
**Describe the bug**
After accessing a _Mixes_ playlist during library analysis, Rune throws a blue screen and becomes unresponsive. Upon checking the Task Manager, it appears that the unresponsive Rune process is still performing analysis and waiting for CPU usage to decrease before restarting. Waited for analysis done, restarted, _Mixes_ works again.

**To Reproduce**
Steps to reproduce:
1. Go to Settings -> Library -> (My library item) -> Analyze or start an analysis from somewhere else.
2. Navigate back to the home page.
3. Click into _Mixes_.
4. Click on a Mix playlist, for example, _Mix 3_. This leads to an interface crash.
5. Kill and relaunch Rune, simply click _Mixes_ from the home page to crash.

**Expected behavior**
The interface should not crash. Maybe consider temporarily disabling access to _Mixes_ and Mix playlists during library analysis or replacing them with an analysis progress/hint page during that time.

**Screenshots**
![](https://github.com/user-attachments/assets/654f3206-cc2e-4a3b-8a83-761898e8e1cb)

**Desktop**
 - OS: Windows 11 21H2 22000.2538
 - Version: Rune-v0.0.0-alpha.19-1d84138-windows

**Comment by Losses** [comment]
Nice catch! Let me have a look about this
