### ISSUE TITLE
Fail to start the app on Android devices

### ISSUE THREAD

**Issue by Dustin-Jiang** [Losses/rune#152]
**Describe the bug**

Rune app fails to start on my Android devices

**To Reproduce**

1. Install the apk of version alpha-20 from the Release page.
2. Start the app and get stuck on the system-generate splash screen. 

**Expected behavior**

The app starts up correctly.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 131
 - Android VM Version: Android 11

**Smartphone (please complete the following information):**
 - Device: Redmi K60 Ultra
 - OS: Android 15

**Additional context**

It seems that the app crashes very early on the startup peroid, because the app does NOT acquire any permission. 

On both devices the behavior is the same.

**Comment by Losses** [comment]
Yep, it's broken as expected since works related to Android has not been kicked off, we will let users know when it's ready.

Thank you for the participation!
