### ISSUE TITLE
Rune interface crashes when attempting to play songs that are no longer available

### ISSUE THREAD

**Issue by puff-dayo** [Losses/rune#171]
**Describe the bug**
When my local music library changes and some songs are deleted due to my cloud synchronization, and I do not manually re-scan the library, attempting to play a song that no longer exists causes the application to completely freeze and become unresponsive. No GUI-visible error message or BSOD error is displayed.

Here is the error message from terminal:

```
2024-12-04T02:27:32.358358Z ERROR hub::media_file: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
2024-12-04T02:27:35.637771Z  INFO playback::internal: Playlist cleared
thread '<unnamed>' panicked at native\hub\src\playback.rs:41:14:
called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
```

**To Reproduce**
1. Modify a local music library by deleting/renaming a song.
2. Run Rune without performing a library re-scan.
3. Attempt to play the song that is no longer available.

**Expected behavior**
Display an error message on GUI indicating that the selected song is no longer available.
Prevent rune from panicking when trying to play on non-existent songs.

**Desktop**
OS: Windows 11 21H2 22000.2538
Version: Rune-v0.0.0-alpha.23-windows-amd64

**Comment by Losses** [comment]
Wow, cool!

**Comment by Losses** [comment]
The bug was fixed, while the file is not found, the player will try to skip the track and continue playing other tracks.

Thank you for the response as always!
