### ISSUE TITLE
Close Button not working and Program icon

### ISSUE THREAD

**Issue by Crocodile73** [Losses/rune#187]
Windows 11 (22631 build x64)

i know its early in development, couple issues that have appeared for me.

1) Taskbar icon disappeared after beta 1 or two
2) Close. Minimize, full screen buttons do not function for me

**Comment by Losses** [comment]
The window control button issue is fixed in [this commit](https://github.com/Losses/rune/commit/5d6e6b036332018555535afe92e560b566257b3e)

About task bar, can you provide more detail about the issue?

**Comment by Crocodile73** [comment]
when i launch the app. And its icon shows on the taskbar, there is no icon for me. It shows a grey square instead of rune's icon. I will get a picture uploaded asap

**Comment by Losses** [comment]
It looks like you are using a customization tool for your task bar, which tool are you using?

**Comment by Losses** [comment]
Happy to see your issue solved, cheers!
