### ISSUE TITLE
Accessing "Mix 8" After Canceling Analysis Causes Missing Metadata Error

### ISSUE THREAD

**Issue by LOTUSSSB** [Losses/rune#216]
**Describe the bug**
When canceling the analysis of tracks in "Mix 8" and returning to the "Library" page, attempting to access "Mix 8" again results in an error message indicating a failure to fetch recommendations due to missing metadata.

**To Reproduce**
1. Go to 'Library'.
2. Click on 'Mixs'.
3. Click on 'Mix 8'.
4. Click on 'Analyze Tracks'.
5. Cancel the analysis.
6. Return to 'Library'.
7. Click on 'Mixs' again.
8. Click on 'Mix 8'.
9. See the error message.

**Expected behavior**
The "Mix 8" page should load normally, displaying the relevant tracks or analysis content without any errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/2c67593e-500f-4a4d-87ef-84a36e5b09e7)

**Desktop (please complete the following information):**
 - OS: Windows11 (26120) 
  System Version 26120 
  Kernel Version26120
- Player  Version
Build Hasha385eea6
Build Date2024-12-12
Commit Date 2024-12-12
Rustc version 1.83.0

**Additional context**
This issue causes subsequent attempts to access the "Mixs" page to fail with the following error:
```
Error {
    context: "Processing signal: FetchCollectionGroupsRequest",
    source: Error {
        context: "Failed to get recommendation by parameters",
        source: MissingMetadata(
            0,
        ),
    },
}
```
![image](https://github.com/user-attachments/assets/96a5a0d2-7552-43c2-b03d-7a67fc4728ee)

**Comment by Losses** [comment]
Oops, I guess the library is not analyzed, let me add a fallback here!
