### ISSUE TITLE
msix file does not run

### ISSUE THREAD

**Issue by clin1234** [Losses/rune#219]
Got This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

**Comment by Losses** [comment]
Yes, the MSIX package is primarily used for publishing on the Microsoft Store, and we haven't made any signing operations for it. If you need it, you might have to sign it yourself, or you can download the ZIP package and use the portable version.

**Comment by Aaron0130yzy** [comment]
> Yes, the MSIX package is primarily used for publishing on the Microsoft Store, 和 we haven't made any signing operations for it. If you need to install Rune with MSIX package, please consider sign it yourself, or you can download the ZIP package and use the portable version.是的，MSIX软件包主要用于在Microsoft Store上发布，和我们尚未为此进行任何签名操作。如果您需要使用MSIX软件包安装符文，请考虑自己签名，或者可以下载ZIP软件包并使用便携式版本。

So, will MSIX file signing be added in future versions? I'm having trouble signing the MSIX package myself and haven't been able to complete it successfully. Even if you don't plan to sign the MSIX package on GitHub, as a customer who purchased the software from the Microsoft Store, I hope the store version can receive timely updates.

**Comment by Losses** [comment]
> > Yes, the MSIX package is primarily used for publishing on the Microsoft Store, 和 we haven't made any signing operations for it. If you need to install Rune with MSIX package, please consider sign it yourself, or you can download the ZIP package and use the portable version.
> 
> So, will MSIX file signing be added in future versions? I'm having trouble signing the MSIX package myself and haven't been able to complete it successfully. Even if you don't plan to sign the MSIX package on GitHub, as a customer who purchased the software from the Microsoft Store, I hope the store version can receive timely updates.


Thank you for your question about MSIX package signing. Let me address your concerns about updates and package signing.

We currently don't have plans to provide signed MSIX packages on GitHub. However, I want to assure you that we actively maintain our software versions across all store platforms. Version 1.1.0 has already been pushed to the Microsoft Store.

To ensure a stable experience for our paid users, we follow a comprehensive process that includes:

1. Careful version management where alpha, beta, and RC versions are never pushed to the store. Most users prefer not to receive automatic updates containing known bugs.

2. A cooling-off period after official releases to verify that binary versions distribute correctly across all software platforms before pushing to users' computers.

While I understand users' eagerness to experience new features, we believe version management requires discipline, prioritizing stability over rapid iteration.

If you're interested in trying the latest features, you can use the ZIP package from GitHub. Apart from an unregistered identifier, it functions identically to the store version. However, please note that cross-version upgrades may alter the database structure, potentially causing compatibility issues with lower-version software.

For Store customers, rest assured that you will receive timely updates through the official Microsoft Store channel, ensuring both stability and security.
