### ISSUE TITLE
PlaybackMode `shuffle` is glitch

### ISSUE THREAD

**Issue by XMLHexagram** [Losses/rune#36]
**Describe the bug**
Playback Mode `shuffle` is full of bugs.

**To Reproduce**
* 1. If the current playlist only have one song, choose this mode and click next song, the app will be frozen.
* 2. In shuffle mode, if you click one song in the mix, it won't play the song that user click.
* 3. In shuffle mode, the previous song is random, not the exactly previous one.

**Expected behavior**
It should work intuitively. We should redesign and refactor this playback mode.

**Comment by Losses** [comment]
Fixed in master.
