### ISSUE TITLE
.rune folders not hidden on Windows

### ISSUE THREAD

**Issue by puff-dayo** [Losses/rune#66]
**Describe the bug**
On Windows, folders starting with a dot (.) are not expected to be hidden. Specifically, all `.rune` folders are visible to users. Is this a bug or an intended feature? 🤔

**To Reproduce**
Add and scan any library with Rune on Windows.

**Desktop**
 - OS: Windows 11 21H2 22000.2538
 - Rune version: v0.0.0-dev.22

**Additional context**
To correctly set a directory to `FILE_ATTRIBUTE_HIDDEN` on Windows, we possibly need to use the Win32 API `SetFileAttributesW`.

**Comment by Losses** [comment]
Nice catch! Let me try to fix this tomorrow!

**Comment by Losses** [comment]
Fixed, It will be released in v0.0.0-alpha.1, thanks!
